pull_request_rules:
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: merge jika semua require sudah terpenuhi
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
    actions:
      comment:
        message: "thank you for your contribution @{{ author }}!"
      label:
        add:
          - sudah di review!
      merge:
        method: squash
